home/urls.py
from django.urls import path
from home.views import *
urlpatterns = [
    path("", home_page, name="home_page"),
    path("jobs/", jobs_page, name="jobs_page"),
    path("contact-api/", contact_api, name="contact_api"),
]

rbzk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500

handler400 = 'error_views.views.bad_request'
handler403 = 'error_views.views.permission_denied'
handler404 = 'error_views.views.page_not_found'
handler500 = 'error_views.views.server_error'

urlpatterns = [
    path('89ee14c8c7cb465faa10ec1a5e142fd3/', admin.site.urls),
    path('', include("home.urls")),
    path('', include("cal_stats.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
import pytz
from django.db import models
from datetime import datetime
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.utils import timezone
from utils.which_week import which_week
from utils.update_week_hours import update_workweek_hours


class WorkWeek(models.Model):
    week_start  = models.DateTimeField()
    week_end    = models.DateTimeField()
    jobs_time   = models.DurationField(null=True)
    
    def __str__(self):
        return f"START: {timezone.localtime(self.week_start):'%m/%d/%Y %H:%M'}  \
            |||  END: {timezone.localtime(self.week_end):'%m/%d/%Y %H:%M'}"
    
    class Meta:
        ordering = ["-week_end"]


class ParkJob(models.Model):
    job_start       = models.DateTimeField()
    job_end         = models.DateTimeField()
    confirmation    = models.CharField(max_length=1024, blank=False, null=True)
    notes           = models.TextField(blank=True, null=True)
    workweek        = models.ForeignKey(WorkWeek, on_delete=models.CASCADE)

    def __str__(self):
        return f"START - {timezone.localtime(self.job_start):%m/%d/%Y %I:%M %p}  \
            |||  END - {timezone.localtime(self.job_end):%m/%d/%Y %I:%M %p}"
    
    class Meta:
        ordering = ["-job_end"]


class FormSubmission(models.Model):
    name = models.CharField(max_length=2024, blank=True, null=True)
    email = models.CharField(max_length=2024, blank=True, null=True)
    phone = models.CharField(max_length=2024, blank=True, null=True)
    message = models.CharField(max_length=2024, blank=True, null=True)
    navigators_match = models.BooleanField(default=False)
    navigator_string_from_request = models.CharField(max_length=2024, blank=True, null=True)
    navigator_string_from_js = models.CharField(max_length=2024, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)

    def __str__(self):
        return f"Submitted by {self.name} on {timezone.localtime(self.created):%m/%d/%Y %I:%M %p}"


@receiver(post_save, sender=ParkJob)
def update_week_hours(sender, instance, **kwargs):
    current_parent_week = instance.workweek
    job_end_time = instance.job_end
    week_start, week_end = which_week(job_end_time)
    if isinstance(week_start, datetime) and isinstance(week_end, datetime):
        new_parent_week, created = WorkWeek.objects.get_or_create(
            week_start=week_start, 
            week_end=week_end
        )
        if created:
            new_parent_week.parkjob_set.add(instance)
            update_workweek_hours(new_parent_week)
            update_workweek_hours(current_parent_week)
        else:
            update_workweek_hours(new_parent_week)
    #kick off a background task to delete all empty workweeks
    empty_work_weeks = WorkWeek.objects.all().exclude(jobs_time__isnull=False)
    for e in empty_work_weeks:
        e.delete()


@receiver(post_delete, sender=ParkJob)
def update_week_hours_after_job_delete(sender, instance, **kwargs):
    work_week = instance.workweek
    update_workweek_hours(work_week)

home/forms.py
from django import forms 
  
# creating a form  
class JobForm(forms.Form): 
    job_start_date = forms.DateTimeField(widget=forms.TextInput(attrs={
        'required': True,
        'placeholder': 'Start Date', 
        'style': 'width: 100%;',
        'class': 'form-control',
        'autocomplete': "off",
    })) 
    job_start_time = forms.DateTimeField(widget=forms.TextInput(attrs={
        'required': True,
        'placeholder': 'Start Time', 
        'style': 'width: 100%;',
        'class': 'form-control',
        'autocomplete': "off",
    })) 
    job_end_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'required': True,
        'placeholder': 'End Date', 
        'style': 'width: 100%; margin-bottom: 20px', 
        'class': 'form-control',
        
        'autocomplete': "off",
    })) 
    job_end_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'required': True,
        'placeholder': 'End Time', 
        'style': 'width: 100%; margin-bottom: 20px', 
        'class': 'form-control',
        'autocomplete': "off",
    }))
    confirmation = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'required': True,
        'placeholder': "Confirmation#",
        'style': 'width: 100%; margin-bottom: 20px', 
        'class': 'form-control',
        'autocomplete': "off",
    }))
    notes = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'placeholder': "Notes",
        'style': 'width: 100%; margin-bottom: 20px', 
        'class': 'form-control'
    }))

home/views.py
import base64
import json
from datetime import datetime

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.gzip import gzip_page
from django.views.decorators.cache import never_cache
from utils.which_week import which_week

from .models import *
from .forms import *


def escape(htmlstring):
    escapes = {'\"': '&quot;',
               '\'': '&#39;',
               '<': '&lt;',
               '>': '&gt;'}
    # This is done first to prevent escaping other escapes.
    htmlstring = htmlstring.replace('&', '&amp;')
    for seq, esc in escapes.items():
        htmlstring = htmlstring.replace(seq, esc)
    return htmlstring


@gzip_page
def home_page(request):
    return render(request, "home.html")


def contact_api(request):
    navigator_from_request = request.META['HTTP_USER_AGENT']
    decoded = request.body.decode('ascii')
    body = json.loads(decoded)
    if "token" in body:
        b_navigator_js = base64.b64decode(body["token"])
        navigator_from_js = escape(b_navigator_js.decode('ascii'))
    if "name" in body["submissionObject"]:
        name = escape(body["submissionObject"]["name"])
    if "email" in body["submissionObject"]:
        email = escape(body["submissionObject"]["email"])
    if "phone" in body["submissionObject"]:
        phone = escape(body["submissionObject"]["phone"])
    if "message" in body["submissionObject"]:
        message = escape(body["submissionObject"]["message"])
    if navigator_from_request == navigator_from_js:
        navigators_match = True

    try:
        FormSubmission.objects.create(
            name=name,
            email=email,
            message=message,
            phone=phone,
            navigators_match=navigators_match,
            navigator_string_from_js=navigator_from_js,
            navigator_string_from_request=navigator_from_request,
        )
    except Exception as e:
        print(e)
    return JsonResponse({"response": 200})

@never_cache
def jobs_page(request):
    if request.user.is_authenticated:
        context = {}
        context['form'] = JobForm()
        context["weeks"] = WorkWeek.objects.all().exclude(jobs_time__isnull=True)
        context["is_logged_in"] = request.user.is_authenticated
        if request.method == "POST":
            data = request.POST
            job_start_date = data.get("job_start_date")
            job_start_time= data.get("job_start_time")
            job_end_date= data.get("job_end_date")
            job_end_time = data.get("job_end_time")
            confirmation = data.get("confirmation")
            notes = data.get("notes")
            
            job_start = job_start_date.strip() + " " + job_start_time.strip()
            job_end = job_end_date.strip() + " " + job_end_time.strip()
            job_start_datetime = timezone.make_aware(datetime.strptime(job_start, '%m/%d/%Y %H:%M'))
            job_end_datetime = timezone.make_aware(datetime.strptime(job_end, '%m/%d/%Y %H:%M'))

            week_start_datetime, week_end_datetime = which_week(job_end_datetime)
            if isinstance(week_start_datetime, datetime) and isinstance(week_end_datetime, datetime):
                week, created = WorkWeek.objects.get_or_create(
                    week_start=week_start_datetime, 
                    week_end=week_end_datetime
                )
                if not created:
                    week.save()
                # add a job to that week
                job, created = ParkJob.objects.get_or_create(
                    job_start=job_start_datetime,
                    job_end=job_end_datetime,
                    confirmation=confirmation,
                    notes=notes,
                    workweek=week,
                )
                if not created:
                    job.save()
            context["weeks"] = WorkWeek.objects.all()
            context["form"] = JobForm()
            return render(request, "jobs.html", context)
        else:
            return render(request, "jobs.html", context)
    else:
        return redirect("home_page")

home/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Personal Portfolio Website, showcasing experience and career of Nick Rebezniuk." />
        <meta name="author" content="Nick Rebezniuk" />
        <title>RBZK</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static '/global/favicon/favicon-32x32.png' %}" />
        <!-- Google fonts-->
        <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700"/>
        <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link type="text/css" rel="stylesheet" href="{% static '/home_page/css/theme-styles.min.css' %}"/>
        <link type="text/css" rel="stylesheet" href="{% static '/home_page/css/custom-styles.css' %}"/>

	    <meta name="robots" content="noindex,nofollow">

    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home_page' %}">RBZK</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">About</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="{% static '/home_page/assets/img/avataaars.svg' %}" alt="..." />
                
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Welcome! I'm Nick.</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0"> Coder - Software Engeneer - Geek </p>
            </div>
        </header>
        <!-- Portfolio Section-->
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Portfolio</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row justify-content-center">
                    <!-- Portfolio Item 1-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <a href="https://github.com/n1ckollas"
                            target="_blank" 
                            rel="noopener noreferrer">
                            <div class="portfolio-item mx-auto">
                                <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                    <div class="portfolio-item-caption-content text-center text-white">
                                        <i class="fas fa-plus fa-3x"></i>
                                        <p>Early work</p>
                                    </div>
                                </div>
                                <img class="img-fluid early-work" src="{% static '/home_page/assets/img/github2.png' %}" alt="GitHub Logo" />
                            </div>
                        </a>
                    </div>
                    <!-- Portfolio Item 2-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <a href="https://www.linkedin.com/in/n1cko/" 
                            target="_blank" 
                            rel="noopener noreferrer">
                            <div class="portfolio-item mx-auto">
                                <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                    <div class="portfolio-item-caption-content text-center text-white">
                                        <i class="fas fa-plus fa-3x"></i>
                                        <p>Career</p>
                                    </div>
                                </div>
                                <div class="career-wrapper">
                                    <img class="img-fluid career" src="{% static '/home_page/assets/img/LinkedIn.png' %}" alt="LinkedIn Logo" />
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- Portfolio Item 3-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <a href="https://github.com/nick-rbzk" target="_blank" rel="noopener noreferrer">
                            <div class="portfolio-item mx-auto">
                                <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                    <div class="portfolio-item-caption-content text-center text-white">
                                        <i class="fas fa-plus fa-3x"></i>
                                        <p>Late Work</p>
                                    </div>
                                </div>
                                <img class="img-fluid late-work" src="{% static '/home_page/assets/img/github2.png' %}" alt="GitHub Logo" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- About Section Content-->
                <div class="row">
                    <div class="col-lg-4 ms-auto">
                        <p class="lead">
                            When I was 18 I got my first pc. 
                            It was windows 98 and I exploded at first sight of it. 
                            I wish I never installed counter-strike on it because it completely messed with my then whispering passion to follow directory to directory in MS-DOS. I liked it. 
                        </p>
                    </div>
                    <div class="col-lg-4 me-auto">
                        <p class="lead">
                            I can still recall it to this day. Time passed, and even being older I still can’t see myself being happy without writing logic, anticipating what it does and having it do exactly what's expected. 
                            When one writes code it’s not the process of writing that excites. It’s finding a solution of a challenge and having a clear vision of how a particular solution is put together and implemented inside a machine. 
                            It’s the most amazing feeling I’ve experienced so far. And I can’t get enough of it!
                        </p>
                    </div>
                </div>
                <!-- About Section Button-->
            </div>
        </section>



    

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        {% if show_contact %}
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            2215 John Daniel Drive
                            <br />
                            Clark, MO 65243
                        </p>
                        {% endif %}
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" 
                        target="_blank" href="https://github.com/nick-rbzk">
                            <i class="fab fa-fw fa-github"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" 
                            target="_blank" href="https://twitter.com/n1cko_rbzk">
                            <i class="fab fa-fw fa-twitter"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" 
                            target="_blank" href="https://www.linkedin.com/in/n1cko/">
                            <i class="fab fa-fw fa-linkedin-in"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" 
                            target="_blank" href="https://github.com/n1ckollas">
                            <i class="fab fa-fw fa-github"></i>
                        </a>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Web Vision, LLC</small></div>
        </div>

        <!-- Font Awesome icons (free version)-->
        <script async src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script async src="{% static 'home_page/js/scripts.min.js' %}"></script>
        <script async src="{% static 'home_page/js/form.js' %}"></script>
    </body>
</html>

home/templates/jobs.html
{% load static %}
{% load duration %}
{% load job_duration %}
{% load income %}
{% load job_income %}
{% load date_format %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>RBZK</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static '/home_page/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />

        <!-- Core theme CSS (includes Bootstrap)-->
        <link type="text/css" rel="stylesheet" href="{% static '/home_page/css/theme-styles.min.css' %}"/>
        <!-- <link type="text/css" rel="stylesheet" href="{% static '/home_page/css/custom-styles.css' %}"/> -->
        <!-- <link type="text/css" rel="stylesheet" href="{% static '/home_page/css/styles.css' %}"/> -->

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <link href="{% static '/home_page/jq-ui/jquery-ui.min.css' %}" rel="stylesheet" />
        <link href="{% static '/home_page/jq-ui/jquery-ui.structure.min.css' %}" rel="stylesheet" />
        <link href="{% static '/home_page/jq-ui/jquery-ui.theme.min.css' %}" rel="stylesheet" />

	    <meta name="robots" content="noindex,nofollow">

        <style>
            .custom-button {
                width: 100%;
            }
            .flex-container{
                display: flex;
                flex-direction: row;
                flex-wrap: wrap;
                justify-content: space-evenly;
		align-items:start;
            }
            .flex-container .custom-card{
                    margin: 10px 0 10px 0;
            }
            .bold-header{
                font-weight: bold;
            }
            .nav-bar-bg {
                background-color: rgba(44, 62, 80, 1) !important;
            }
        </style>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg nav-bar-bg text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home_page' %}">RBZK</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'admin:index' %}">
                                Admin
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="page-section portfolio">
            <div class="container-fluid mt-5">
                <div class="row mt-2">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-1 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
                            <div class="col-10 col-sm-10 col-md-8 col-lg-6 col-xl-4">
                                <h2 class="page-section-heading text-center text-uppercase text-secondary mt-5 mb-2">
                                    Add A Job
                                </h2>
                                <form action="{% url 'jobs_page' %}" method="post">
                                        {% csrf_token %}
                                    <div class="row">
                                        <div class="col mt-2 mb-2">
                                            {{ form.job_start_date }}
                                        </div>
                                        <div class="col mt-2 mb-2">
                                            {{ form.job_start_time}}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col mt-2 mb-2">
                                            {{ form.job_end_date}}
                                        </div>
                                        <div class="col mt-2 mb-2">
                                            {{ form.job_end_time}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        {{ form.confirmation }}
                                    </div>
                                    <div class="form-group">
                                            {{ form.notes }}
                                    </div>
                                    <div class="form-group">
                                        <input class="btn btn-success custom-button" 
                                        type="submit" value="Submit">
                                    </div>
                                </form>
                            </div>
                            <div class="col-1 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="page-section portfolio">
            <div class="container-fluid">
                <hr>
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-5">
                    Job Records
                </h2>
                <div class="flex-container mt-5">
                        {% for w in weeks %}
                        <div class="card custom-card">
                            <div class="card-header">
                                <h6 class="bold-header">
                                    Week: {{ w.week_start|date_format }} -> {{w.week_end|date_format }}
                                </h6>
                            </div>
                            <ul class="list-group list-group-flush">
                                {% for j in w.parkjob_set.all %}
                                <li class="list-group-item">
                                    <span class="badge bg-warning text-dark">{{ forloop.counter }}</span> | 
                                    {{ j.job_start|date_format }} -> {{j.job_end|date_format}}
                                    <span class="badge badge-primary">CONF# {{ j.confirmation}}</span>
                                    <span class="badge badge-info">{{ j|job_duration }}</span>
                                    =
                                    <span class="badge badge-success">{{ j|job_income }}</span>
                                </li>
                                {% endfor %}
                            </ul>
                            <div class="card-footer">
                                <h6 class="bold-header">Total:
                                    <span class="badge badge-info">
                                        {{ w.jobs_time|duration }}
                                    </span>
                                    <span class="badge badge-success">
                                        {{ w.jobs_time|income }}
                                    </span>
                                </h6>
                            </div>
                        </div>
                        {% endfor %}
                </div>
            </div>
        </section>
        
        <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="{% static '/home_page/jq-ui/jquery-ui.min.js' %}"></script>
        <script>
            function formatTime(val){
                if(val.length >= 5 && val.indexOf(":") > 0){
                    return val 
                }
                var firstFour = val.substring(0, 4).split("")
                var hours = null;
                var mins = null;
                if(firstFour.length >= 4){
                    hours = firstFour[0] + firstFour[1]
                    mins = firstFour[2]+ firstFour[3]
                }
                if(hours && mins){
                    return hours + ":" + mins;
                }
                return null;
            }
            $('#id_job_start_time').on("blur", function(value){
                $(this).val(formatTime($(this).val()))
            });
            $('#id_job_end_time').on("blur", function(value){
                $(this).val(formatTime($(this).val()))
            });
            $("#id_job_start_date").datepicker();
            $("#id_job_end_date").datepicker();
        </script>
    </body>
</html>